import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import { Space_Grotesk, Work_Sans } from "next/font/google";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import { site } from "@/data/site";
import "./globals.css";

const gaId = process.env.NEXT_PUBLIC_GA_ID;

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — ${site.tagline}`,
    template: `%s | ${site.name}`,
  },
  description: site.description,
  keywords: [
    "Corplabs",
    "software company Malaysia",
    "AI WhatsApp agent",
    "custom software Malaysia",
    "Odoo ERP Malaysia",
    "MyInvois",
    "website design Malaysia",
  ],
  // og/twitter title + description are intentionally omitted so each page's
  // own title/description flow into them automatically. The og/twitter image
  // is generated by app/opengraph-image.tsx and cascades to every route.
  // Canonical is per-page (a layout-level canonical would point every page at "/").
  openGraph: {
    type: "website",
    siteName: site.name,
    url: site.url,
    locale: "en_MY",
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${workSans.variable} ${spaceGrotesk.variable}`}>
      <body className="bg-surface font-sans text-zinc-200 antialiased">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
      {gaId && <GoogleAnalytics gaId={gaId} />}
    </html>
  );
}
