import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import { Inter, Work_Sans } from "next/font/google";
import { CurrencyProvider } from "@/components/currency/currency-context";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import { SiteChrome } from "@/components/layout/site-chrome";
import { site } from "@/data/site";
import { themeInitScript } from "@/lib/theme";
import "./globals.css";

const gaId = process.env.NEXT_PUBLIC_GA_ID;

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — ${site.tagline}`,
    template: `%s | ${site.name}`,
  },
  description: site.description,
  keywords: [
    "Corplabs",
    "software company Malaysia",
    "AI WhatsApp agent",
    "custom software Malaysia",
    "Odoo ERP Malaysia",
    "MyInvois",
    "website design Malaysia",
  ],
  // og/twitter title + description are intentionally omitted so each page's
  // own title/description flow into them automatically. The og/twitter image
  // is generated by app/opengraph-image.tsx and cascades to every route.
  // Canonical is per-page (a layout-level canonical would point every page at "/").
  openGraph: {
    type: "website",
    siteName: site.name,
    url: site.url,
    locale: "en_MY",
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${workSans.variable} ${inter.variable}`}
      suppressHydrationWarning /* themeInitScript sets data-theme before React sees it */
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="bg-surface font-sans text-zinc-200 antialiased">
        <CurrencyProvider>
          <SiteChrome header={<Header />} footer={<Footer />}>
            {children}
          </SiteChrome>
        </CurrencyProvider>
      </body>
      {gaId && <GoogleAnalytics gaId={gaId} />}
    </html>
  );
}
